id: P9FFBE200
initial_creation_type: ocr
source_metadata:
  volumes:
    059173783fb04fe3a43d2f0080d813c4:
      base_file: v096.txt
      image_group_id: I1PD95941
      title: བཤེས་པའི་སྤྲིང་ཡིག།
      total_pages: 1144
      volume_number: 96
